# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ImageDialog.ui'
#
# Created: Sun May  3 16:39:12 2009
#      by: PyQt4 UI code generator 4.4.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_imageDialog(object):
    def setupUi(self, imageDialog):
        imageDialog.setObjectName("imageDialog")
        imageDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        imageDialog.resize(342, 233)
        self.gridlayout = QtGui.QGridLayout(imageDialog)
        self.gridlayout.setObjectName("gridlayout")
        self.groupBox = QtGui.QGroupBox(imageDialog)
        self.groupBox.setObjectName("groupBox")
        self.gridlayout1 = QtGui.QGridLayout(self.groupBox)
        self.gridlayout1.setObjectName("gridlayout1")
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.vboxlayout = QtGui.QVBoxLayout()
        self.vboxlayout.setObjectName("vboxlayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.vboxlayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.vboxlayout.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.vboxlayout.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.vboxlayout.addWidget(self.label_4)
        self.hboxlayout.addLayout(self.vboxlayout)
        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.txtURL = QtGui.QLineEdit(self.groupBox)
        self.txtURL.setObjectName("txtURL")
        self.vboxlayout1.addWidget(self.txtURL)
        self.txtDesc = QtGui.QLineEdit(self.groupBox)
        self.txtDesc.setObjectName("txtDesc")
        self.vboxlayout1.addWidget(self.txtDesc)
        self.comboAlignment = QtGui.QComboBox(self.groupBox)
        self.comboAlignment.setObjectName("comboAlignment")
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.comboAlignment.addItem(QtCore.QString())
        self.vboxlayout1.addWidget(self.comboAlignment)
        self.hboxlayout1 = QtGui.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.spinX = QtGui.QSpinBox(self.groupBox)
        self.spinX.setObjectName("spinX")
        self.hboxlayout1.addWidget(self.spinX)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.hboxlayout1.addWidget(self.label_5)
        self.spinY = QtGui.QSpinBox(self.groupBox)
        self.spinY.setObjectName("spinY")
        self.hboxlayout1.addWidget(self.spinY)
        self.vboxlayout1.addLayout(self.hboxlayout1)
        self.hboxlayout.addLayout(self.vboxlayout1)
        self.gridlayout1.addLayout(self.hboxlayout, 0, 0, 1, 1)
        self.hboxlayout2 = QtGui.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.insertBttn = QtGui.QPushButton(self.groupBox)
        icon = QtGui.QIcon()
        icon.addFile("/usr/share/pixmaps/chotha/ok.png")
        self.insertBttn.setIcon(icon)
        self.insertBttn.setObjectName("insertBttn")
        self.hboxlayout2.addWidget(self.insertBttn)
        spacerItem = QtGui.QSpacerItem(21, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hboxlayout2.addItem(spacerItem)
        self.cancelBttn = QtGui.QPushButton(self.groupBox)
        icon1 = QtGui.QIcon()
        icon1.addFile("/usr/share/pixmaps/chotha/dialog-cancel.png")
        self.cancelBttn.setIcon(icon1)
        self.cancelBttn.setObjectName("cancelBttn")
        self.hboxlayout2.addWidget(self.cancelBttn)
        self.gridlayout1.addLayout(self.hboxlayout2, 1, 0, 1, 1)
        self.gridlayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(imageDialog)
        QtCore.QMetaObject.connectSlotsByName(imageDialog)

    def retranslateUi(self, imageDialog):
        imageDialog.setWindowTitle(QtGui.QApplication.translate("imageDialog", "Insert Image....", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("imageDialog", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("imageDialog", "Image URL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("imageDialog", "Image Descrption", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("imageDialog", "Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("imageDialog", "Dimensions", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(0, QtGui.QApplication.translate("imageDialog", "-- Not Set --", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(1, QtGui.QApplication.translate("imageDialog", "Baseline", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(2, QtGui.QApplication.translate("imageDialog", "Top", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(3, QtGui.QApplication.translate("imageDialog", "Middle", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(4, QtGui.QApplication.translate("imageDialog", "Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(5, QtGui.QApplication.translate("imageDialog", "Text Top", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(6, QtGui.QApplication.translate("imageDialog", "Absolute Middle", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(7, QtGui.QApplication.translate("imageDialog", "Absolute Bottom", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(8, QtGui.QApplication.translate("imageDialog", "Left", None, QtGui.QApplication.UnicodeUTF8))
        self.comboAlignment.setItemText(9, QtGui.QApplication.translate("imageDialog", "Right", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("imageDialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.insertBttn.setText(QtGui.QApplication.translate("imageDialog", "Insert", None, QtGui.QApplication.UnicodeUTF8))
        self.cancelBttn.setText(QtGui.QApplication.translate("imageDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

